name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Get the most recent JAR file from S3
        id: get_latest_jar
        run: |
          latest_jar=$(aws s3api list-objects-v2 --bucket aichat-s3 --query "Contents[?ends_with(Key, '.jar')].[Key,LastModified]" --output text | sort -k2,2r | head -n 1 | awk '{print $1}')
          echo "Latest JAR file: $latest_jar"
          echo "LATEST_JAR=$latest_jar" >> $GITHUB_ENV

      - name: Download JAR from S3
        run: |
          aws s3 cp s3://aichat-s3/${{ env.LATEST_JAR }} ./your-file.jar

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: 43.202.245.31  # 퍼블릭 IP 주소
          username: ec2-user   # 기본 사용자 이름
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Stopping existing service..."
            sudo systemctl stop your-service || true
            
            echo "Removing old JAR..."
            sudo rm -f /path/to/your/old-file.jar
            
            echo "Copying new JAR..."
            sudo cp ~/your-file.jar /path/to/your/new-file.jar
            
            echo "Starting service..."
            sudo systemctl start your-service
